# Generated by Django 4.0.5 on 2022-06-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_album_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set(),
        ),
    ]
