# Generated by Django 4.0.5 on 2022-06-12 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_delete_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorappointment', to='appointment.doctor'),
        ),
    ]
