# Generated by Django 4.0.5 on 2022-06-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_alter_doctorappointment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.RemoveField(
            model_name='doctorappointment',
            name='kind',
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='visit_type',
            field=models.CharField(choices=[('New-Patient', 'New-Patient'), ('Follow-up', 'Follow-up')], default='New-Patient', max_length=20),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
