# Generated by Django 4.0.5 on 2022-06-14 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_remove_track_album_remove_doctorappointment_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.DurationField()),
            ],
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctorappointment', to='appointment.doctor'),
        ),
    ]
