# Generated by Django 4.0.5 on 2022-06-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_test_alter_doctorappointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='appointment_time',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
    ]
