# Generated by Django 4.0.5 on 2022-06-15 04:35

import appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0019_alter_test_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='appointment_time',
            field=models.DateTimeField(validators=[appointment.models.future]),
        ),
    ]
