# Generated by Django 4.0.5 on 2022-06-15 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_alter_doctorappointment_appointment_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
